# Generated by Django 3.0.5 on 2020-05-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20200519_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Description',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
