# Generated by Django 3.0.5 on 2020-05-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20200519_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Title',
            field=models.CharField(max_length=500),
        ),
    ]
